# Generated by Django 6.0.2 on 2026-03-24 05:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('senha', models.CharField(max_length=128)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, unique=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('tipo', models.CharField(choices=[('pessoal', 'Pessoal'), ('institucional', 'Institucional')], default='institucional', max_length=15)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.usuario')),
            ],
            options={
                'verbose_name': 'Aluno',
                'verbose_name_plural': 'Alunos',
            },
            bases=('api.usuario',),
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.usuario')),
            ],
            options={
                'verbose_name': 'Professor',
                'verbose_name_plural': 'Professores',
            },
            bases=('api.usuario',),
        ),
        migrations.CreateModel(
            name='Questao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questoes', to='api.materia')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questoes_criadas', to='api.professor')),
            ],
        ),
        migrations.CreateModel(
            name='Alternativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=255)),
                ('eh_correta', models.BooleanField(default=False)),
                ('questao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alternativas', to='api.questao')),
            ],
        ),
        migrations.CreateModel(
            name='RespostaAluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('esta_correta', models.BooleanField(default=False)),
                ('data_resposta', models.DateTimeField(auto_now_add=True)),
                ('alternativa_marcada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='respostas_marcadas', to='api.alternativa')),
                ('questao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas', to='api.questao')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas', to='api.aluno')),
            ],
        ),
        migrations.CreateModel(
            name='MateriaPessoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, unique=True)),
                ('criador', models.ForeignKey(blank=True, help_text='Aluno responsável ( para matérias pessoais)', null=True, on_delete=django.db.models.deletion.CASCADE, to='api.aluno')),
            ],
        ),
        migrations.AddField(
            model_name='materia',
            name='aluno',
            field=models.ForeignKey(blank=True, help_text='Aluno responsável (para matérias pessoais)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='materias_pessoais', to='api.aluno'),
        ),
        migrations.CreateModel(
            name='Flashcard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=120)),
                ('pergunta', models.TextField()),
                ('resposta', models.TextField()),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flashcards', to='api.materia')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flashcards', to='api.aluno')),
            ],
        ),
        migrations.CreateModel(
            name='MateriaInstitucional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, unique=True)),
                ('criador', models.ForeignKey(blank=True, help_text='Professor responsável (para matérias institucionais)', null=True, on_delete=django.db.models.deletion.CASCADE, to='api.professor')),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.AddField(
            model_name='materia',
            name='professor',
            field=models.ForeignKey(blank=True, help_text='Professor responsável (para matérias institucionais)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='materias_institucionais', to='api.professor'),
        ),
    ]
