# Generated by Django 6.0.2 on 2026-03-24 04:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flashcard',
            name='titulo',
        ),
        migrations.AlterField(
            model_name='alternativa',
            name='eh_correta',
            field=models.BooleanField(default=False, help_text='Indica se esta alternativa é a correta.'),
        ),
        migrations.AlterField(
            model_name='alternativa',
            name='questao',
            field=models.ForeignKey(help_text='Questão à qual a alternativa pertence.', on_delete=django.db.models.deletion.CASCADE, related_name='alternativas', to='api.questao'),
        ),
        migrations.AlterField(
            model_name='alternativa',
            name='texto',
            field=models.CharField(help_text='Texto da alternativa.', max_length=255),
        ),
        migrations.AlterField(
            model_name='flashcard',
            name='aluno',
            field=models.ForeignKey(help_text='Aluno responsável pela criação do flashcard.', on_delete=django.db.models.deletion.CASCADE, related_name='flashcards', to='api.aluno'),
        ),
        migrations.AlterField(
            model_name='flashcard',
            name='materia',
            field=models.ForeignKey(help_text='Matéria à qual o flashcard pertence.', on_delete=django.db.models.deletion.CASCADE, related_name='flashcards', to='api.materia'),
        ),
        migrations.AlterField(
            model_name='flashcard',
            name='pergunta',
            field=models.TextField(help_text='Pergunta principal do flashcard.'),
        ),
        migrations.AlterField(
            model_name='flashcard',
            name='resposta',
            field=models.TextField(help_text='Resposta do flashcard.'),
        ),
        migrations.AlterField(
            model_name='materia',
            name='criador',
            field=models.ForeignKey(help_text='Professor responsável pela criação da matéria.', on_delete=django.db.models.deletion.CASCADE, related_name='materias_criadas', to='api.professor'),
        ),
        migrations.AlterField(
            model_name='materia',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, help_text='Data de criação da matéria.'),
        ),
        migrations.AlterField(
            model_name='materia',
            name='nome',
            field=models.CharField(help_text='Nome da matéria.', max_length=120),
        ),
        migrations.AlterField(
            model_name='questao',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, help_text='Data de criação da questão.'),
        ),
        migrations.AlterField(
            model_name='questao',
            name='materia',
            field=models.ForeignKey(help_text='Matéria à qual a questão pertence.', on_delete=django.db.models.deletion.CASCADE, related_name='questoes', to='api.materia'),
        ),
        migrations.AlterField(
            model_name='questao',
            name='professor',
            field=models.ForeignKey(help_text='Professor responsável pela criação da questão.', on_delete=django.db.models.deletion.CASCADE, related_name='questoes_criadas', to='api.professor'),
        ),
        migrations.AlterField(
            model_name='respostaaluno',
            name='alternativa_marcada',
            field=models.ForeignKey(blank=True, help_text='Alternativa marcada pelo aluno, quando houver.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='respostas_marcadas', to='api.alternativa'),
        ),
        migrations.AlterField(
            model_name='respostaaluno',
            name='aluno',
            field=models.ForeignKey(help_text='Aluno que respondeu a questão.', on_delete=django.db.models.deletion.CASCADE, related_name='respostas', to='api.aluno'),
        ),
        migrations.AlterField(
            model_name='respostaaluno',
            name='data_resposta',
            field=models.DateTimeField(auto_now_add=True, help_text='Data em que a resposta foi enviada.'),
        ),
        migrations.AlterField(
            model_name='respostaaluno',
            name='esta_correta',
            field=models.BooleanField(default=False, help_text='Indica se a resposta do aluno está correta.'),
        ),
        migrations.AlterField(
            model_name='respostaaluno',
            name='questao',
            field=models.ForeignKey(help_text='Questão respondida pelo aluno.', on_delete=django.db.models.deletion.CASCADE, related_name='respostas', to='api.questao'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, help_text='Data de criação do usuário.'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(help_text='E-mail único do usuário.', max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nome',
            field=models.CharField(help_text='Nome completo do usuário.', max_length=150),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='senha',
            field=models.CharField(help_text='Senha cadastrada para acesso ao sistema.', max_length=128),
        ),
    ]
