# Generated by Django 6.0.2 on 2026-04-30 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_flashcard_titulo_alter_alternativa_eh_correta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alternativa',
            name='eh_correta',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='alternativa',
            name='texto',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='flashcard',
            name='pergunta',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='flashcard',
            name='resposta',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='materia',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='materia',
            name='nome',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='respostaaluno',
            name='data_resposta',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='respostaaluno',
            name='esta_correta',
            field=models.BooleanField(default=False),
        ),
    ]
