# Generated by Django 6.0.2 on 2026-05-16 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_alternativa_eh_correta_alter_alternativa_texto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questao',
            name='enunciado',
            field=models.CharField(default=True, max_length=255),
        ),
    ]
